### ISSUE TITLE
Textures don't work in-game on first load, F3+T fixes it

### ISSUE THREAD

**Issue by jbredwards** [CleanroomMC/AssetMover#10] opened 2023-03-09 05:03 UTC
https://github.com/jbredwards/Subaquatic/issues/20

AssetMover works fine from my end, but is there anything I should be doing in my mod's code to ensure this doesn't happen? Right now my mod is calling `AssetMoverAPI.fromMinecraft` to download the textures during `FMLConstructionEvent`.

**Comment by Rongmario** [comment] 2023-03-09 13:43
Duplicate of #1, I'll investigate it after work.

**Closed** 2023-03-09 18:40 UTC
